#!/bin/python

import os

def install_apache():
    print("installing apache server")
    os.system('sudo yum -y install httpd')


    print("enabling apache server")
    os.system('sudo systemctl enable httpd.service')

    print("starting apache server")
    os.system('sudo systemctl start httpd.service')


    print("If you open the security settings for port 80 on your server, you should see the apache start page")
install_apache()
